### ISSUE TITLE
Deprecated keyEvent

### ISSUE THREAD

**Issue by Hirse** [bryanjhv/brackets-tab-tags#3]
> Registering for deprecated event 'keyEvent'. Instead, use 'keydown/press/up'
>    at _activeEditorChangeHandler (file:///C:/Users/d056950/AppData/Roaming/Brackets/extensions/user/tab-tags/main.js:69:24)

As of Brackets 1.1 the [`keyEvent` is considered deprecated](https://github.com/adobe/brackets/wiki/Release-Notes:-1.1#api-changes):
> Editor's "keyEvent" event is deprecated. Use the more specific events "keyup", "keypress", or "keydown" instead. (However, in most cases you should use Document's "change" event instead of any of the Editor events).

**Comment by bryanjhv** [comment]
Thanks for the deprecation notice, now it's fixed! :smile:
