### ISSUE TITLE
Not working on my Mac.

### ISSUE THREAD

**Issue by MrBodira** [bryanjhv/brackets-tab-tags#5]
When I use this extention on Brackets for Mac (Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 
build timestamp: Mon May 11 2015 02:49:32 GMT-0700) and I type for example &lt;p&gt;&lt;/p&gt; and the cursor is between the >< and I enter, it's not doing the tab like your example.

It only brings the cursor on a new line. This test is done in a php file and html file. In the html file it did tab but the and tag was stil on the same line after the tab.

**Comment by AlexanderOtavka** [comment]
I have the same problem (same brackets release).  Currently running brackets on Mac OS Yosemite.

**Comment by blah73** [comment]
Curious if this is related to issue #6  maybe?  I have a pull request that fixed my issue.

**Comment by MrBodira** [comment]
Thanks blah73, it is related to issue #6 the fix solved the problem.

**Comment by bryanjhv** [comment]
Hey @MrBodira, could you please test the fix and let me know if it works, along with other little changes I made, merging #4, #7 and some code?

**Comment by MrBodira** [comment]
Hey Bryan, it works like a charm. There are some small issues I get from jsLint/jsHint.
line 14: Bad line breaking before '?': ? '\t' [[ you can't break a line  before a '?']]
line 15: Missing 'new' prefix when invoking a constructor: Array(editor._getOption('spaceUnits')+1).join(' ')
But they are no show stoppers.
Thanks for the update.

**Comment by bryanjhv** [comment]
Yes, I got same errors, but for now I'm leaving code linting.
Ok, thanks. Closing issue :)
