### ISSUE TITLE
Not working in windows after reload

### ISSUE THREAD

**Issue by blah73** [bryanjhv/brackets-tab-tags#6]
When I install this extension everything works great until I close Brackets.

After I close and reopen Brackets this extension no longer works.  My other extensions continue to work but not this one.  if I uninstall this package and reinstall... it starts working again.

OS:  Windows 7 Pro 
Brackets: Release 1.3 build 1.3.0-16022 (release cd0a6aae5) 

Tonight I plan on testing this on Ubuntu 14.04.  Will see if this issue is isolated to the OS or not.

**Comment by Nikomtis** [comment]
I have the same problem on Windows 8.1.

**Comment by blah73** [comment]
Yup same issue on Ubuntu.

**Comment by iNarek** [comment]
Same thing over here.

**Comment by bryanjhv** [comment]
Hmm... Can you list all the extensions installed? I currently have only Emmet and my extension, everything working fine in the same release using Ubuntu 14.04 LTS.
The problem I'm facing, instead, is if I type `<DOCTYPE html>`, closing the tag turns into `<DOCTYPE html></DOCTYPE>` but for sure it is a problem from Brackets.

**Comment by blah73** [comment]
Extensions on my Ubuntu machine:  Beautify, Brackets Color Picker, Extract for Brackets (Preview), LESS AutoCompile, Tab tags

For what it's worth on my windows machine i removed all extensions and then installed tab tags and the issue still persisted.

**Comment by bryanjhv** [comment]
None of the listed extensions are conflictive. Please see comment on #7 and let me know :smile:

**Comment by bryanjhv** [comment]
Guys, please try the "new" version in order to close this #5, this and #7.
