### ISSUE TITLE
Work with CSS / LESS?

### ISSUE THREAD

**Issue by thybzi** [bryanjhv/brackets-tab-tags#9]
Would be great to use like:
```
.myclass {
    |
}
```

**Comment by bryanjhv** [comment]
Brackets already supports that at least with CSS :smile: What version of brackets are you using? I'm using `Brackets 1.3 release cd0a6aae5`.

**Comment by thybzi** [comment]
Ok, but what about LESS? :) many people write LESS code instead of CSS.
I can rewrite my pull request if you prefer

**Comment by bryanjhv** [comment]
I know all of one today prefer LESS & SASS to work, but at least at what I've seen in Brackets, the support for auto indenting is present, and I do not want to reinvent the wheel.
Please try first to reload Brackets with extensions disabled, and try, if it is not working paste here a sample code in where the issue reproduces, so I can see :smile: BTW for me it is working fine.

**Comment by thybzi** [comment]
Just rechecked in my Brackets 1.3 release cd0a6aae5 (Win8.1), running without extensions.
In **both CSS and LESS** pressing Enter between curly brackets on code like:
```
.myclass {}
```

produces ugly:
```
.myclass {
|}
```

instead of beautiful:
```
.myclass {
    |
}
```

**Comment by bryanjhv** [comment]
Ok, I tried what you are saying using Windows 8 SL and Ubuntu 14.04 LTS and no error is present, but maybe in other platforms isn't working. As the fix has no side effects (at least in my tests), it is now merged.
Thanks for the contribution :smiley:
